### ISSUE TITLE
Linker does not find the vncgl library

### ISSUE THREAD

**Issue by hebel23** [uwerat/vnc-eglfs#16]
/usr/bin/ld: cannot find -lvncgl

**Comment by uwerat** [comment]
Guess this happens, when building the platformproxy ?

Did you build the library in src before ? When using the project file from the project root both should be built in the correct order.
The required libvncgl.so is the result of the build in src and should end up in a src/lib directory. Can you find it on your system ?

**Comment by hebel23** [comment]
I just opened the vnceglfs.pro file in QT creator and got this error.
You mean I have to open src.pro at first?

**Comment by hebel23** [comment]
When I remove the -lvncgl parameter - it works!

![grafik](https://user-images.githubusercontent.com/36878925/180389651-9b4ec5dc-4b12-4a6c-a16a-0c9fa6d04a2c.png)

**Comment by uwerat** [comment]
Well, vnceglfs.pro simply defines the 2 subprojects "src" and "platformproxy", where the second depends on the first ( look at the code ). Not sure what the creator is doing in your environment, but in general it should be able to execute qmake project files properly.

But anyway: the VNC server is in libvncgl.so and you definitely need this library. The platformproxy is just a helper to load and initialize the server without having to change application code. When doing the initialization in application code you don't need the platformproxy at all.

In case vnceglfs.pro is absolutely not working for you you can build the library using src/src.pro first and then build the platformproxy in a second step.

**Comment by eduardcazacu** [comment]
I ran into the same issue and solved it by butchering the .pro files with the following patch:

```
diff --git a/platformproxy/platformproxy.pro b/platformproxy/platformproxy.pro
index ef24e8d..5a9b676 100644
--- a/platformproxy/platformproxy.pro
+++ b/platformproxy/platformproxy.pro
@@ -23,14 +23,22 @@ PROJECT_ROOT = $$clean_path( $$PWD/../src )
 INCLUDEPATH *= $${PROJECT_ROOT}
 DEPENDPATH *= $${PROJECT_ROOT}
 
-LIBS *= -L$${PROJECT_ROOT}/lib -lvncgl
+INCLUDEPATH += ../src/lib/
+LIBS += ../src/lib/libvncgl.so
+PRE_TARGETDEPS += ../src/lib/libvncgl.so
 
 SOURCES += \
     VncProxyPlugin.cpp
 
 OTHER_FILES += metadata.json
 
-INSTALL_ROOT=/usr/local/vnceglfs
+INSTALL_ROOT=/usr/lib
 # INSTALL_ROOT=$$[QT_INSTALL_PREFIX]
 
 target.path = $${INSTALL_ROOT}/plugins/platforms
diff --git a/src/src.pro b/src/src.pro
index 29e5fad..ba10d3e 100644
--- a/src/src.pro
+++ b/src/src.pro
@@ -61,7 +61,7 @@ SOURCES += \
     VncClient.cpp \
     VncNamespace.cpp \
 
-INSTALL_ROOT=/usr/local/vnceglfs
+INSTALL_ROOT=/usr
 # INSTALL_ROOT=$$[QT_INSTALL_PREFIX]
 
 target.path = $${INSTALL_ROOT}/lib
```
Perhaps this can help you find a neater fix.
